---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(magrittr)

binding <- read.csv("data/FcRn-binding.csv", comment.char = "#", na.strings = "-", stringsAsFactors = F)

binding %<>% reshape2::melt(id.vars = c("Measurement", "pH"), variable.name = "Antibody") %>%
  mutate(value = as.numeric(gsub("_.*", "", value)))

bindingSel <- filter(binding, grepl("Kd", Measurement)) %>%
  filter(!grepl("low", Measurement)) %>% filter(!grepl("med", Measurement))

bindingc <- reshape2::dcast(bindingSel, Antibody ~ Measurement + pH)
```




```{r}
invivo <- read.csv("data/FcRn-invivo.csv",
                   comment.char = "#",
                   stringsAsFactors = F)


invivo[, 2] <- as.numeric(gsub("_.*", "", invivo[, 2]))
invivo[, 3] <- as.numeric(gsub("_.*", "", invivo[, 3]))
invivo[, 4] <- as.numeric(gsub("_.*", "", invivo[, 4]))


all <- full_join(bindingc, invivo, by = c("Antibody", "Antibody"))
```

```{r}
ggplot(all, aes(x = all[,2], y = AUC, color = all[,3])) + geom_point()
```

