---
title: "FcRn trafficking analysis"
output: pdf_document
---

```{r, message=FALSE, warning=FALSE}
library(fcrn)
library(rstan)
library(magrittr)
library(dplyr)
library(cowplot)

scarlette <-  as.data.frame(summary(loadsample("scarlette"))$summary)
scarlette$param <- row.names(scarlette)
scarlette$model <- factor("scarlette")

diff <-  as.data.frame(summary(loadsample("diff"))$summary)
diff$param <- row.names(diff)
diff$model <- factor("diff")

marlene <-  as.data.frame(summary(loadsample("marlene"))$summary)
marlene$param <- row.names(marlene)
marlene$model <- factor("marlene")

all <- rbind(scarlette, marlene, diff)
rm(diff)
rm(marlene)
rm(scarlette)


assertthat::assert_that(max(all$Rhat) < 1.1)
assertthat::assert_that(min(all$n_eff) > 100)

all %<>% select(-mean, -se_mean, -sd, -n_eff, -Rhat) %>%
  mutate(param = as.factor(param)) %>%
  filter(param != "lp__") %>%
  filter(param != "sortF_wt") %>%
  filter(param != "sortF_dhs") %>%
  filter(param != "sortF_ls") %>%
  filter(param != "releaseF_ls")
```
X

```{r}
globs <- all %>% filter(param == "Q" | param == "Qu" | param == "Vin" | param == "Vp")

ggplot(globs, aes(x = interaction(model, param), y = `50%`, color = model)) + geom_point() +
  geom_errorbar(aes(ymin = `25%`, ymax = `75%`)) + theme(axis.text.x = element_text(angle = 45, hjust = 1))
```


