# Test and build the model output

name: CI

on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Install R
    - uses: r-lib/actions/setup-r@v1

    - name: Test
      run: |
        Rscript -e 'devtools::install_deps("./fcrn")'
        R CMD INSTALL --no-multiarch --with-keep.source fcrn
        Rscript -e 'covr::to_cobertura(covr::package_coverage("./fcrn", quiet = F))'

    - name: Make output
      run: make all
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
    
    - name: Save output
      uses: actions/upload-artifact@v2
      with:
        name: Output
        path: output.pdf
